#默认使用配置
spring:
  profiles:
    active: dev


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/worker?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.huawei.oss.action_manager.pojo
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
    - com.huawei.oss.action_manager.utils.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#server:
#  servlet:
#    session:
#      timeout: 60m